import = ["packages/versioning/Build", "packages/database/Build", "bin/Scripts"]

[project]
name = "flagpole"
version = "0.1.0"

[tasks]
clean = { info = "remove binary", script = ["rm flagpole", "maid butler clean"] }
start = { info = "run binary", script = "bin/flagpole" }
version = { script = "./version_system", info = "set package version" }
