[tasks.build_auth]
path = "packages/authentication"
info = "build server binary"
cache = { path = "packages/authentication", target = "bin/services/auth" }
script = ["go mod tidy" ,"go build .", "mv auth %{dir.current}/bin/services/auth", "echo built auth (main.go)"]