[package]
name = "flagpole_db"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-slog = "0.2.1"
actix-web = "4.3.1"
bytes = "1.4.0"
chrono = "0.4.24"
clap = "4.2.7"
env_logger = "0.10.0"
h2 = "0.3.19"
log = "0.4.17"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
sled = "0.34.7"
slog-json = "2.6.1"
time = "0.3.21"
tokio = "1.28.1"
tracing = "0.1.37"
tracing-actix-web = "0.7.4"
tracing-bunyan-formatter = "0.3.7"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
