[tasks.build_server]
path = "packages/server"
info = "build & run server"
cache = { path = "packages/server", target = "bin/services/server.js" }
script = ["yarn ci", "mv build/app.dist.js %{dir.current}/bin/services/server.js", "yarn clean"]