[tasks.build_versioning]
path = "packages/versioning"
info = "build versioning binary"
cache = { path = "packages/versioning", target = "version_system" }
script = ["cargo build --release", "maid move ../../ version_system %{dir.current}/version_system -q"]