[package]
name = "version_system"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
colored = "2.0.0"
inquire = "0.6.2"
macros-rs = "0.4.0"
regex = "1.8.1"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = { version = "1.0.96", features = ["preserve_order"] }
termcolor = "1.2.0"
toml_edit = "0.19.8"
